# -*- coding: utf-8 -*-
"""OOPS.ipynb documents to reach 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzLlVtR8Ztpb1fo4DXNVdKY_6fZR_zlC

# **OOPS **

OOPS pillars blocks

Encapsulation : capsule , it is combination of many things, putting things together, we are putting together all properties and functions together


Abstracton : we know how to apply functions like drive , turn AC, change gear which are visible but there are things which are hidden as well example in engine


Inheritance. Class Car has subclass Sedan/Suv/Sports. subclass can do everthing what class do and can do additional things . Like Mukesh ambani and Akash Ambani. Aksh can do thingf rom his father plus few additonal things. These are new classes inheriting from existing classes and other more responsibilites. Teacher— HOD,   Student—monitor


Polymorphism.   anything which it chnage form and change . SOmething that can moulds it’s functionality example + operator , example Mohit+Srivastava,    4+9 , example pop funcion behaves diffrently in their own enviorment in list vs set

CONSTRUCTORS

Constructor is special method it is called when an object of class created, in python no direct access to constructors

a= Random()
	__init__() — initialise

	life span

	__del__()— delete


Whenever class is called in order to initiate the class we use __init__
as soon as init is called it gives life to object
init work as constructor but is not construtor
life span is till the time __del is called nit destructor
"""

class Student():
#methods
#properties
  pass

# create a instance of student
s1=Student()

type(s1)

#to check if any object belong to any class

isinstance(s1,Student)

class Student:
  def hello():
    print('Hello Mohit Srivastava')

s1=Student()
s1

# how to access function of class
s1.hello()

--any method which is created in class should have one default parameter which is self
--self says method has to be exuted on object of class
self means one of the things which does inside this method is object itself

class Student:
  def hello(self):
    print('Hello all')

s1=Student()
s1

s1.hello()

--so technically what happens is in backgroud  is s1 goes inside hello(s1) and executes  i.e. s1.hello(s1) and which is why we reserve self keyword

so self is creating PlaceHolder for object , self represents object itself.

example for list

a=[1,2,3]

a.append(4)   # so what happens is a.append(a,4)

#INIT method--it is used to hold for properties


class Student:
  def __init__(self,name,age):
    self.name=name  # here self.name is property
    self.age=age

s1=Student('Mohit',40)    #here __init__ is giving life to object by passing paraments
print(s1.age)
print(s1.name)

s2=Student()

s2=Student('Kian',8)
s2.name   # here s2.name is property

# VARIABLE


class variable and instance variance

class variable is shared across all instances of class , no matter whatever object you create they will have same ValueError
example : Bank phone no remains same


instance variable is unique to each object of class, can have diffrent value to different instances
example : Bank customers name

class Dog:
  kind = 'canine' # class variable

  def __init__(self,name):
    self.name=name

d1=Dog('Tommy')
d2=Dog('Tuffy')

d1.name, d2.name

d1.kind, d2.kind

# permission to change

# value of object can be access outside of class
#instance variable can be updated outside of class

d1.name='Scooby'
d1.name

d1.kind='Bull dog'  # this becomes instance variable

d1.kind,d2.kind,d1.kind

#Here what is happning whenever you wanted to update class variable, if you do it will not give the error however it will create instance
variable in class and add value to it and become global

class Student:

  name='BIPIN'  # class variable

  def __init__(self,name,age):
    self.name=name
    self.age=age

  def hello(self):
    print(f'Hello {self.name}')

bipin =Student('Ayush',20)

bipin.hello()

# so this means every time you call self.name it is instance variable which is caled not class variable

if instance and class variable has same name instance variable will be called out by object

# Dunder Method or magic method


class Car:
  def __init__(self,name,mileage):
    self.name=name
    self.mileage=mileage

c1=Car('Nexon',12)
c2=Car('Citron',15)

c1

# __main__ means object belong to class in current code

What should be printed is in our control

x=2
print(type(x))

#means  object belong to class int which is present everywhere in python

#We use __str__ to tell what should be printed

class Car:
    def __init__(self, name, mileage):
        self.name = name
        self.mileage = mileage

    def __str__(self):
        return f"{self.name} -> {self.mileage}"

c3=Car('Nexon',12)
c4=Car('Citron',15)

print(c3)

##We call these as magic methods because these methods are called automatically example __init__ we dont have to call them

# addition

class Car:
    def __init__(self, name, mileage):
        self.name = name
        self.mileage = mileage

    def __str__(self):
        return f"{self.name} -> {self.mileage}"

    def __add__(self,other):  # other is object of class car
        return self.mileage+other.mileage

    #here we are defining dunder method add for two object , self is object for current class , other is also for same class

c3=Car('Nexon',12)
c4=Car('Citron',15)

c3+c4

#less than

class Car:
    def __init__(self, name, mileage):
        self.name = name
        self.mileage = mileage

    def __str__(self):
        return f"{self.name} -> {self.mileage}"

    def __add__(self,other):  # other is object of class car
        return self.mileage+other.mileage

    def __lt__(self,other):
      return self.mileage<other.mileage

c3=Car('Nexon',12)
c4=Car('Citron',15)

c3<c4

c3>c4

c3==c4

c3=Car('Nexon',12)
c4=Car('Citron',12)

c3==c4  # becase == behaviour is not defined

class Car:
    def __init__(self, name, mileage):
        self.name = name
        self.mileage = mileage

    def __str__(self):
        return f"{self.name} -> {self.mileage}"

    def __add__(self,other):  # other is object of class car
        return self.mileage+other.mileage

    def __lt__(self,other):
      return self.mileage<other.mileage

    def __eq__(self,other):
      return self.mileage==other.mileage

c3=Car('Nexon',12)
c4=Car('Citron',12)

c3==c4

# Inheritance

class Parent:
  def __init__(self):
    #self.a=a
    print("parent class")

class Child(Parent):     # whenever you inherit from class we pass ()
  def __init__(self):
    #self.a=a
    print("chlild class")

p=Parent()

c=Child()

class School_member:
  def __init__(self,name):
    self.name=name

class Student(School_member):
  def __init__(self, name,grade):
    self.grade=grade

class Staff(School_member):
  def __init__(self, name,salary):
      self.salary=salary

class Teacher(School_member):
  def __init__(self, name,salary,subject):
       self.subject=subject

s1=Student('Mohit','A')
print(type(s1))

s1.grade

s1.name

'''access to parent class property denied
We never indicate that name has to be called
like there is lot of struggle while inherit propert untill there is will

so techincally we need to use certain functions which showcase this is getting inheritted'''

#so everytime if i need to inherit i need to include super so name is included everywhere

class School_member:
  def __init__(self,name):
    self.name=name

class Student(School_member):
  def __init__(self, name,grade):
    super().__init__(name)
    self.grade=grade

class Staff(School_member):
  def __init__(self, name,salary):
      super().__init__(name)
      self.salary=salary

class Teacher(Staff):
  def __init__(self, name,salary,subject):
      super().__init__(name,salary)
      self.subject=subject

s1=Student('Mohit','A')
print(type(s1))

s1.name

t1=Teacher('Kian',1000,'python')

t1.name,t1.salary,t1.subject

#Private properties

class BankAcoount:

  def __init__(self,balance):
    self.balance=balance

  def withdraw(self,withdraw_amount):
    self.balance  -= withdraw_amount

  def deposit(self,deposist_amount):
    self.balance  += deposist_amount

b1=BankAcoount(1000)

b1.deposit(500)
b1.balance

b1.withdraw(1500)
b1.balance

# can we directly update balance without withdrawl / depost

b1.balance= 123445
print(b1.balance)

#here balance is getting update so we use private property we use __

class BankAcoount:

  def __init__(self,balance):
    self.__balance=balance

  def withdraw(self,withdraw_amount):
    self.__balance  -= withdraw_amount

  def deposit(self,deposist_amount):
    self.__balance  += deposist_amount

b2=BankAcoount(1000)
b2.__balance    ##We are unable to access directly as this is private property

b2.deposit(1000)
b2.withdraw(500)

'''whenever we make private property we can only change it by certain ways only which are called as getters and setters

Setters: Are set of functions through which we can chnage the value of private property

Getters : Getters are function or methods through we get the values

class BankAcoount:

  def __init__(self,balance):
    self.__balance=balance

  #setters
  def withdraw(self,withdraw_amount):
    self.__balance  -= withdraw_amount
  #setters
  def deposit(self,deposist_amount):
    self.__balance  += deposist_amount

  #setters

  def check_balance(self):
    return self.__balance

b2=BankAcoount(1000)

b2.__balance

b2.deposit(1000)
b2.withdraw(500)

b2.check_balance()

b2.__balance=0
b2.check_balance()  # this remains same and not harming anything as we use private property

dir(b2)

b2._BankAcoount__balance

b2._BankAcoount__balance=0
b2.check_balance()    # here i can make change

class A:
   def one(self):
       return self.two()  # A
   def two(self):
       return 'A'
class B(A):
   def two(self):
       return 'B'

obj= B()

print(obj.one())

#Multiple inheritance

One child class inherting from Two parent class  ex: Mom and Dad


trouser and winter clother both wil have proce tag. now i am creating child class Discount

class A:
  def __init__(self,a):
    self.a=a

class B:
  def __init__(self,b):
    self.b=b

###We define self for own customization but willrun without self

##class C:
  ##pass

class C(A,B):
  def __init__(self,a,b,c):
    #super().__init__(a,b)
    #Super will inherit from immidiate parent

#Soluton is

class C(A,B):
  def __init__(self,a,b,c):
    A.__init__(self,a)  # from A class get init method and from there get all variable required
    B.__init__(self,b)
    self.c=c

c1=C(1,2,3)
print(type(c1))

c1.c

class C(A,B):
  def __init__(self,a,b):
    A.__init__(self,a)  # from A class get init method and from there get all variable required and this csn be used for single parent

    self.b=b

# Method resolution order

#Diamond shape inheritance

prigramming ambiguity which one to chose variable when subclass going to class accessing values

Order : sreach left to right
        We go parent when all child are consumed

class A:
  pass

class B(A):
  pass

class C(B):
  x=10

class D(A):
  x=5

class E(C,D):
  pass

e=E()
e.x

E.__mro__